version: "3.9"
services:
  neo4j-server:
    image: neo4j
    volumes:
      - ./neo4j/data:/data
    ports:
      - "7474"
      - "7687"
    networks:
      - backend
  # server:
  #  build: ./server
  #  network: backend
  #  environment:
  #    - NEO4J_SERVER=neo4j-server
networks:
  backend:
